### ISSUE TITLE
Import/ModuleNotFoundError

### ISSUE THREAD

**Issue by TheBrainninja** [jose-l-martins/GSM-to-Ludusavi-converter#1]
Hello, when attempting to launch main.py after satisfying the python package requirements (pip install [package] either succeeding or saying "requirement already satisfied"), I receive the following error (I apologize for the long filepath)
`c:\Program Files (writable)\GSM_to_Ludosavi_Converter\GSM-to-Ludusavi-converter-master>python main.py --gui
Traceback (most recent call last):
  File "c:\Program Files (writable)\GSM_to_Ludosavi_Converter\GSM-to-Ludusavi-converter-master\main.py", line 7, in <module>
    from ludusavi_mapping_generator import create_ludusavi_mapping
  File "c:\Program Files (writable)\GSM_to_Ludosavi_Converter\GSM-to-Ludusavi-converter-master\ludusavi_mapping_generator.py", line 9, in <module>
    from registry_processor import convert_reg_to_yaml
  File "c:\Program Files (writable)\GSM_to_Ludosavi_Converter\GSM-to-Ludusavi-converter-master\registry_processor.py", line 8, in <module>
    from file_operations import compute_sha1
  File "c:\Program Files (writable)\GSM_to_Ludosavi_Converter\GSM-to-Ludusavi-converter-master\file_operations.py", line 9, in <module>
    from special_path_resolver import resolve_special_path
  File "c:\Program Files (writable)\GSM_to_Ludosavi_Converter\GSM-to-Ludusavi-converter-master\special_path_resolver.py", line 3, in <module>
    import userpaths
ModuleNotFoundError: No module named 'userpaths'`

I'm not well-versed enough in Python to know what this could be; I did open each referenced python script to see where it references "userpaths," but it only appears to be in special_path_resolver.py where it opens with `import userpaths` and then later on under `def resolve_special_path`, `special_paths =  {..."VIDEOS": userpaths.get_my_videos(),` and so on for the standard windows home folder contents. I'm running this from the account whose files I wish to access, so ostensibly it should be able to pull that info, if requested correctly? I'm not sure if there's something I've done wrong here or not - thinking about it, I do have a few of these folders located on a different drive with the location changed in the windows GUI. My Home folder does list my Downloads, Videos, etc. libraries which _do_ show my files when opened, but that's the only wrinkle I can think of.

Do you have any insight into how to resolve this? Your tool seems really handy, as I've been using GSM for years and would like to switch over now that I've found Ludosavi!

**Comment by jose-l-martins** [comment]
Hi there,

Sorry for the late reply, and thank you for reporting this issue! I’m glad you find the tool interesting. In the meantime, I’ve updated and fixed several things, so I recommend downloading the latest version.

The issue here was that I had forgotten to add the `userpaths` package to the repository description (`README.md`), mentioning it only in the `requirements.txt` file. To resolve this, please run `pip install userpaths`. Additionally, I’ve updated the tool to use `ruamel.yaml` instead of `PyYAML` for better YAML parsing. Be sure to also run `pip install ruamel.yaml`.

I’ve updated the repository description to reflect these changes and clarified the _flags_ and _arguments_ used to run the program to make them less ambiguous.

With the latest updates, I’ve also fixed several bugs and resolved outdated issues. From my testing, it’s working well, though further optimizations are still planned.

If you prefer, I’ve also created a self-contained `.exe` executable for the GUI using `PyInstaller`. You can try it out here: [[Version 1.0.0 - gsm_ludusavi_converter.exe](https://github.com/jose-l-martins/GSM-to-Ludusavi-converter/releases/download/v1.0.0/gsm_ludusavi_converter.exe)](https://github.com/jose-l-martins/GSM-to-Ludusavi-converter/releases/download/v1.0.0/gsm_ludusavi_converter.exe).

**Note**: Please ensure you keep the original backup source files for a while and don’t delete them immediately after converting them into a new format. On rare occasions, some information might be missing in the converted files, and having the originals allows you to restore anything that might be lost. I’ve added this suggestion to the repository description as well. Both GameSave Manager and Ludusavi provide "validation" scans to help confirm whether the process was successful. Only delete files when you’re absolutely sure you no longer need them, and even then, I recommend erring on the side of caution.

I plan to make the tool more robust and comprehensive in a future update to eliminate any remaining uncertainty.

Let me know if you encounter any other issues!

**Comment by myrmeleontidae** [comment]
Olá, desculpe por me intrometer!

I figure it's okay if I piggyback and necro-bump since it's a tangentially related issue.

Is using 'pip' the intended way to install the necessary Python modules? I only ask because right now 

`$ pip install win32com`

results in
```
ERROR: Could not find a version that satisfies the requirement win32com (from versions: none)
ERROR: No matching distribution found for win32com
```

The only other module pip couldn't install was:
`$ pip install pypiwin32`
```
Collecting pypiwin32
  Downloading pypiwin32-223-py3-none-any.whl (1.7 kB)
  Downloading pypiwin32-219.zip (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 4.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bs26cn6e/pypiwin32_be8577b96d52445ea98672177e9e31b9/setup.py", line 121
          print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any insights or workarounds? I'm relatively unfamiliar with Python's ecosystem, so I _guess_ bugging the modules' respective maintainers could be in the cards, but in the meantime your tool may have to be shelved. But it's a really _cool_ tool, and I support it, haha. Just might have to start a few games' worth of progress over again. No biggie!

Oh, running Pop!_OS after making the long walk off a short plank from Windows 10
